In [ ]:
import os
from glob import glob
import time

from bs4 import BeautifulSoup
import pandas as pd
from selenium import webdriver
from selenium.webdriver.support.ui import Select
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support.expected_conditions import presence_of_all_elements_located

In [ ]:
data = pd.read_excel(
    os.path.expanduser('~/Downloads/esklp_20241107_excel_00001/esklp_smnn_20241107.xlsx'), sheet_name=1,
) # pip install openpyxl
data.head()

/home/laks/310env/lib/python3.10/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,Стандартизованное МНН,Код узла СМНН,Код ОКПД 2,Стандартизованная лекарственная форма,Стандартизованная дозировка,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Единица измерения лекарственного препарата,...,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Список нормализованных МНН для узла СМНН,Список нормализованных лекарственных форм и дозировок для узла СМНН,КЛП,Некорректные данные
0,NaN,NaN,NaN,NaN,Кол-во,Единица измерения,NaN,NaN,Описание,NaN,...,Диапазон II количества единиц измерения лекарс...,NaN,Значение цены III,Диапазон III количества единиц измерения лекар...,NaN,Показатель среднеквадратичного отклонения (σ),NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,Наименование,Код ОКЕИ,Наименование единицы из ОКЕИ,NaN,Наименование,...,Минимальное,Максимальное,NaN,Минимальное,Максимальное,NaN,NaN,NaN,Ссылка,NaN
2,1,2,3,4,5,6,7,8,9,10,...,28,29,30,31,32,33,34,35,36,37
3,1-(4-БРОМФЕНИЛ)ВИОЛУРОВАЯ КИСЛОТА,21.20.10.114-000050-1-00082-0000000000000,21.20.10.114,КАПСУЛЫ,500,мг,161,мг,500 мг,шт. (капсула),...,NaN,NaN,NaN,NaN,NaN,NaN,1-(4-БРОМФЕНИЛ)ВИОЛУРОВАЯ КИСЛОТА,КАПСУЛЫ (500 мг),esklp_klp_20241107_00000.xlsx,NaN
4,1-[2-(1-МЕТИЛИМИДАЗОЛ-4-ИЛ)-ЭТИЛ]ПЕРГИДРОАЗИН-...,21.20.10.214-000057-1-00001-0000000000000,21.20.10.214,ТАБЛЕТКИ,100,мг,161,мг,100 мг,шт. (таблетка),...,NaN,NaN,NaN,NaN,NaN,NaN,1-[2-(1-МЕТИЛИМИДАЗОЛ-4-ИЛ)-ЭТИЛ]ПЕРГИДРОАЗИН-...,ТАБЛЕТКИ (100 мг),esklp_klp_20241107_00000.xlsx,NaN

In [ ]:
data.columns

Index(['Стандартизованное МНН', 'Код узла СМНН', 'Код ОКПД 2',
       'Стандартизованная лекарственная форма', 'Стандартизованная дозировка',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8',
       'Единица измерения лекарственного препарата', 'Unnamed: 10',
       'Unnamed: 11', 'Наименование ФТГ', 'АТХ', 'Unnamed: 14', 'ЖНВЛП',
       'Наличие в лекарственном препарате наркотических средств, психотропных веществ и их прекурсоров',
       'Период действия узла СМНН', 'Unnamed: 18', 'Дата изменения записи',
       'Референтные цены (приведенные значения цен, в соответствии с письмом Минздрава России, являются средневзвешенные по Российской Федерации и справочными)',
       'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24',
       'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28',
       'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31', 'Unnamed: 32',
       'Список нормализованных МНН для узла СМНН',
       'Список нормализованных лекарственных форм и дозировок для узла СМНН',
       'КЛП', 'Некорректные данные'],
      dtype='object')

In [ ]:
data = data[~data['Наименование ФТГ'].isna()][3:]
data.head()

,Стандартизованное МНН,Код узла СМНН,Код ОКПД 2,Стандартизованная лекарственная форма,Стандартизованная дозировка,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Единица измерения лекарственного препарата,...,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Список нормализованных МНН для узла СМНН,Список нормализованных лекарственных форм и дозировок для узла СМНН,КЛП,Некорректные данные
5,"2,8-ДИМЕТИЛ-5-(2-ФЕНИЛЭТИЛ)-2,3,4,5-ТЕТРАГИДРО...",21.20.10.235-000143-1-00002-0000000000000,21.20.10.235,"ТАБЛЕТКИ, ПОКРЫТЫЕ ОБОЛОЧКОЙ",20,мг,161,мг,20 мг,шт. (таблетка),...,NaN,NaN,NaN,NaN,NaN,NaN,"2,8-ДИМЕТИЛ-5-(2-ФЕНИЛЭТИЛ)-2,3,4,5-ТЕТРАГИДРО...",ТАБЛЕТКИ ПОКРЫТЫЕ ПЛЕНОЧНОЙ ОБОЛОЧКОЙ (20 мг),esklp_klp_20241107_00000.xlsx,NaN
6,4-НИТРО-N-[(1RS)-1-(4-ФТОРФЕНИЛ)-2-(1-ЭТИЛПИПЕ...,21.20.10.141-000047-1-00045-0000000000000,21.20.10.141,КОНЦЕНТРАТ ДЛЯ ПРИГОТОВЛЕНИЯ РАСТВОРА ДЛЯ ВНУТ...,1,мг/мл,876,усл. ед,1 мг/мл,мл,...,NaN,NaN,NaN,NaN,NaN,NaN,4-НИТРО-N-[(1RS)-1-(4-ФТОРФЕНИЛ)-2-(1-ЭТИЛПИПЕ...,КОНЦЕНТРАТ ДЛЯ ПРИГОТОВЛЕНИЯ РАСТВОРА ДЛЯ ВНУТ...,esklp_klp_20241107_00000.xlsx,NaN
7,"7,9-ДИБРОМ-2Н-[1]БЕНЗОПИРАНО[2,3-D]ПИРИМИДИН-2...",21.20.10.191-000129-1-00045-0000000000000,21.20.10.191,КАПСУЛЫ,250,мг,161,мг,250 мг,шт. (капсула),...,NaN,NaN,NaN,NaN,NaN,NaN,"7,9-ДИБРОМ-2Н-[1]БЕНЗОПИРАНО[2,3-D]ПИРИМИДИН-2...",КАПСУЛЫ (250 мг),esklp_klp_20241107_00000.xlsx,NaN
8,ARANEUS DIADEMATUS+HEKLA-LAVA+KALIUM JODATUM+А...,21.20.10.251-000777-1-00005-0000000000000,21.20.10.251,ТАБЛЕТКИ ГОМЕОПАТИЧЕСКИЕ,1,~,876,усл. ед,~,шт. (таблетка),...,NaN,NaN,NaN,NaN,NaN,NaN,~,ТАБЛЕТКИ ДЛЯ РАССАСЫВАНИЯ ГОМЕОПАТИЧЕСКИЕ (НЕ ...,esklp_klp_20241107_00000.xlsx,NaN
9,CHINA RUBRA+АДРЕНАЛИНУМ+ВИНКА МИНОР+ГАМАМЕЛИС ...,21.20.10.251-000807-1-00004-0000000000000,21.20.10.251,КАПЛИ ГОМЕОПАТИЧЕСКИЕ,1,~,876,усл. ед,~,мл,...,NaN,NaN,NaN,NaN,NaN,NaN,~,КАПЛИ ДЛЯ ПРИЕМА ВНУТРЬ ГОМЕОПАТИЧЕСКИЕ (НЕ УК...,esklp_klp_20241107_00000.xlsx,NaN

In [ ]:
data = data[data['Наименование ФТГ'].str.contains('противоопухолевое')]

In [ ]:
downloaded = pd.read_csv('Instructions/instr_metadata.tsv', sep='\t',header=None)
downloaded.tail()
# метаданные всех инструкций, которые мы выкачали
# объяснение метаданных:
# 0 - Стандартизованное МНН, оно же действующее вещество
# 1 - торговое наименование
# 2 - ID лекарства в ГРЛС, из которого можно составить адрес его странички
# 3 - путь до PDF с инструкцией. Пользуясь им, можно найти файл инструкции в выгрузке ({uuid}.pdf)
# записи могут дублироваться, если одна и та же инструкция скачалась > 1 раза (во время дебага например)

,0,1,2,3
565,Этопозид,Этопозид-Тева,28404765-6f64-49da-94a4-4079fe7ab37d,https://grls.rosminzdrav.ru/InstrImg/2023/11/3...
566,Этопозид,Фитозид,eac03547-ea20-413a-b976-9151deb254c4,https://grls.rosminzdrav.ru/InstrImg/2022/01/1...
567,Этопозид,Ластет,5c2006a5-ffd6-487e-8330-2f2ab2619c46,https://grls.rosminzdrav.ru/InstrImg/2015/10/2...
568,Этопозид,Ластет,82190c01-9445-4799-a905-c166ee76a7bc,https://grls.rosminzdrav.ru/InstrImg/2020/05/2...
569,Этопозид,Этопозид-Эбеве®,8fdf4e0b-077d-4aef-9bb0-b99b749b1218,https://grls.rosminzdrav.ru/InstrImg/2021/10/2...

Открываем файл с метаданными в режиме "дописывания" (загрузка иногда прерывалась из-за каптчи. Каптча у них древняя, не было уверенности, что готовые библиотеки для решения reCaptcha подойдут)

In [ ]:
f = open('instr_metadata.tsv', 'a', encoding='utf8')

In [ ]:
options = webdriver.FirefoxOptions()
driver = webdriver.Firefox(options=options)
# запускаем Фаерфокс в режиме бота только один раз. В настройках выбираем действия с pdf - сохранить на диск.
# (это должно было быть возможно автоматизировать через FirefoxProfile, но не сработало)
# так же можно выбрать папку, куда сохранять (по умолчанию это обычная папка Downloads, куда падают все загрузки
# из браузеров)

In [ ]:
for key in data['Стандартизованное МНН'].unique():
    key = key.strip()
    key = key[0] + key[1:].lower()
    if (key not in downloaded[0].values) and (key not in {
        'Арглабин', 'Белок теплового шока gp-96', 'Гефитиниб', 'Коикса семян масло'}):
        # у этих веществ нет лекарств с инструкциями
        print(key)
        wait = WebDriverWait(driver, 10)
        driver.get("https://grls.rosminzdrav.ru/GRLS.aspx")
        wait = WebDriverWait(driver, 10)
        driver.find_element(By.ID, 'ctl00_plate_txtMNN').send_keys(key)
        wait = WebDriverWait(driver, 10)
        driver.find_element(By.ID, 'ctl00_plate_bSeek').click()
        html = driver.page_source
        soup = BeautifulSoup(html, 'html.parser')
        els = soup.find_all(class_='hi_sys poi')
        for el in els:
            time.sleep(5)
            wait = WebDriverWait(driver, 10)
            onclick = el['onclick'].split("'")[1]
            filename = onclick + '.pdf'

            driver.get(f"https://grls.rosminzdrav.ru/Grls_View_v2.aspx?routingGuid={onclick}")
            time.sleep(10)
            name = driver.find_element(By.ID, 'ctl00_plate_TradeNmR').get_attribute('value')
            print(name)

            driver.find_element(By.ID, 'instructionsCaller').click()
            time.sleep(10)
            try:
                iframe = driver.find_element(By.TAG_NAME, 'iframe')
            except Exception as e:
                # bad practice. По-хорошему надо было бы найти, откуда селениум берет NoSuchElementError
                # и исключать только её
                # это обработка случая, когда инструкции нет
                print(e)
                continue
            path = iframe.get_attribute('src')
            driver.switch_to.frame(iframe)

            f.write(key + '\t' + name + '\t' + onclick + "\t" + path +'\n')

Лизомустин
Ралтитрексед
Тегафур+урацил
Фактор некроза опухоли альфа-1 [тимозин рекомбинантный]
Цитарабин
ЦИТАРАБИН-РУС
Алексан®
Цитарабин-ЛЭНС®
Цитарабин
Цитозар®
Эверолимус
ЭВЕРОЛИМУС
ЭВЕРОЛИМУС
ЭВЕЛИРОК®
Афинитор®
Афинитор®
СЕЙВНОВИ®
Эверолимус-АМЕДАРТ
Сертикан®
Алвида®
ЭВЕРОЛИМУС-ПРОМОМЕД
Эксеместан
Эксеместан-ТЛ
Аромазин®
Элотузумаб
Эмплисити®
Эпирубицин
Эпирубицин-Рус
Эпирубицин-РОНЦ®
Эпирубицин-Келун-Казфарм
Эпирубицин
Фарморубицин® быстрорастворимый
Эрлотиниб
Эрлатера
ЭРЛОТИНИБ-ТЛ
Эрлотиниб
Эрлотиниб
Эрлотиниб-натив
Эрлотиниб
Этопозид
Этопозид-Рус
Этопозид-ЛЭНС®
Фитозид
Филотид
Этопозид
Этопозид-Тева
Фитозид
Ластет
Ластет
Этопозид-Эбеве®

In [ ]:
f.close() # не забудь закрыть после того, как предыдущая ячейка упала с каптчей, иначе не запишется

In [ ]:
# remove duplicated files created while debugging

for path in glob('Instructions/*).pdf'):
    print(path)
    os.remove(path)

Instructions/a967d2ef-a0f1-4371-b71d-0c86e79df628(1).pdf
Instructions/91cb1f69-3eab-424c-94e3-58cef7a03ba0(1).pdf
Instructions/09dbf80f-3cfe-4a2c-82c4-7683ab829172(1).pdf
Instructions/3baf33a6-4020-4d89-91e6-fac72f9bd0fd(1).pdf
Instructions/c6a71699-819e-40a6-a9d3-1a383fa5021f(1).pdf
Instructions/4136123e-fb3f-46a4-9def-aa1517f4d70a(1).pdf
Instructions/5c34e22a-7052-4213-8d64-a0400017807e(1).pdf
Instructions/8709d2e9-8a9f-4a27-a2c8-2258352d112c(1).pdf
Instructions/5a1ebe55-1f7b-443e-a2f6-46d77bd08074(1).pdf
Instructions/7dd7abb0-5932-4476-9a31-5375c903d666(1).pdf
Instructions/d48ef54d-05ce-4a24-8ad8-bcd344ce21fc(1).pdf
Instructions/4a950323-f8c2-4292-9858-59b3591c9b44(2).pdf
Instructions/237cf73e-af1e-49ee-af73-7a3f121608f2(1).pdf
Instructions/58ac3835-4b49-4ba5-bd4e-5c1e414ee154(1).pdf
Instructions/b355dfd5-ae69-4d24-846d-0f82adfb0fc6(1).pdf
Instructions/4a950323-f8c2-4292-9858-59b3591c9b44(1).pdf
Instructions/af2607fd-1618-4d65-aeab-d73b6ee86cf2(1).pdf
Instructions/44863a63-8baf-446a-a044-79fc1e43e299(1).pdf
Instructions/59cb8af2-29ed-4c29-972e-19fa88d788be(2).pdf
Instructions/b0829a84-34aa-4b6b-b8c6-c3c3346f8b3a(1).pdf
Instructions/1295d9cc-c22e-4af2-86aa-49fbf56e2376(1).pdf
Instructions/10034290-0be1-4080-8da0-afcbe942a82e(2).pdf
Instructions/10856e35-8729-4e22-8bae-eb6f1720b619(1).pdf
Instructions/863f6555-9a46-4720-bd87-9ee8ef3436aa(2).pdf
Instructions/4ccbba96-d51c-4f24-afb2-116825d5acd7(1).pdf
Instructions/9636e639-9f46-4fb8-8d53-da4bddfd0c4b(3).pdf
Instructions/ЛП-006064[2020]_0(1).pdf
Instructions/915b58bd-6732-455a-9a10-9f875bc9b44b(1).pdf
Instructions/ЛП-000398[2019]_0(1).pdf
Instructions/026c21c8-8957-43e4-b721-d69996fc8267(1).pdf
Instructions/23d7aebb-65b5-40bd-86ce-f1d02017faac(1).pdf
Instructions/7811d0cf-d24d-4ac5-a738-899fec7fbf3b(1).pdf
Instructions/bd1433a2-c290-4ca4-b4e6-5160fcaec66d(1).pdf
Instructions/69182e47-092a-4703-8740-a4487407581a(1).pdf
Instructions/ЛП-003171[2020]_0(1).pdf
Instructions/026f142c-5b7e-4275-bb05-8439a9a7c92a(1).pdf
Instructions/7471c9a3-15e3-4a55-9840-6b2dd1f98f78(1).pdf
Instructions/c4ccac51-8455-45a4-95a1-1eaa0ef5452f(1).pdf
Instructions/9636e639-9f46-4fb8-8d53-da4bddfd0c4b(2).pdf
Instructions/40b224fb-f79e-4b05-a7a0-882b48c7bb80(1).pdf
Instructions/ЛСР-008999_09[2020]_0(1).pdf
Instructions/75f21b3f-edb1-4898-a65d-f942b0fb9a3a(1).pdf
Instructions/c5c1c9ba-f473-4474-bd00-10ba56b548d5(1).pdf
Instructions/57bc0ff3-b8d3-4d69-b4c9-a98e12036376(1).pdf
Instructions/c0880ddb-afe2-4873-b644-0fd8e8e5b875(1).pdf
Instructions/9636e639-9f46-4fb8-8d53-da4bddfd0c4b(1).pdf
Instructions/2a64decb-d44c-48e1-8c36-caaa5b515538(1).pdf
Instructions/0407b4f2-4b96-4cb4-8d2b-ed0e227e7da1(1).pdf
Instructions/10570265-ea19-4c7b-9c41-14e5c4922052(1).pdf
Instructions/9d3baa37-5171-4fb7-abfb-b53655cd0b22(1).pdf
Instructions/afbee0f1-f99e-4c24-91d7-134606e2040b(1).pdf
Instructions/7517515e-aa2c-435f-9ec3-332919e4945e(1).pdf
Instructions/45de0dd5-64fa-403d-b599-76b9df9c1b64(1).pdf
Instructions/863f6555-9a46-4720-bd87-9ee8ef3436aa(3).pdf
Instructions/45de0dd5-64fa-403d-b599-76b9df9c1b64(2).pdf
Instructions/026f86ab-6a65-4ce2-bcee-0f8285b64024(1).pdf
Instructions/536f4f8b-f2f4-48cf-8e29-a733e166c2a5(1).pdf
Instructions/704b4eca-7828-4cf8-ad20-68f11299dd88(1).pdf
Instructions/8709d2e9-8a9f-4a27-a2c8-2258352d112c(2).pdf
Instructions/863f6555-9a46-4720-bd87-9ee8ef3436aa(4).pdf
Instructions/5caffe56-b932-453d-977d-f7a22a897703(2).pdf
Instructions/bb8b2ac3-66fe-4bee-a48c-4152acb9043b(1).pdf
Instructions/5563ede4-6ca2-416e-95e1-45d130831338(1).pdf
Instructions/d591c764-01c3-469e-a081-c498f3dcd1c7(2).pdf
Instructions/216c8cf9-0cdf-42a6-901a-44ed00c8b548(2).pdf
Instructions/d591c764-01c3-469e-a081-c498f3dcd1c7(1).pdf
Instructions/6a877eb5-2e0f-4fa2-bedd-cd8b1aa0c55e(1).pdf
Instructions/6a66e36e-8980-418e-85c1-f9f7c9d58a99(1).pdf
Instructions/b1e6ad08-1b71-4c9e-bb4c-8063dd317b7a(1).pdf
Instructions/59cb8af2-29ed-4c29-972e-19fa88d788be(1).pdf
Instructions/d03add2d-42d5-49b5-a8af-6eb6ff71a58b(1).pdf
Instructions/216c8cf9-0cdf-42a6-901a-44ed00c8b548(1).pdf
Instructions/10034290-0be1-4080-8da0-afcbe942a82e(1).pdf
Instructions/af2607fd-1618-4d65-aeab-d73b6ee86cf2(2).pdf
Instructions/afbee0f1-f99e-4c24-91d7-134606e2040b(2).pdf
Instructions/9827b109-bf15-4bdc-84d4-2d4b7be944ae(1).pdf
Instructions/1b8eea2e-5c53-4e06-8982-b7edd4c55159(1).pdf
Instructions/ЛП-001205[2017]_0(1).pdf
Instructions/863f6555-9a46-4720-bd87-9ee8ef3436aa(1).pdf
Instructions/c81f6359-272c-429a-9aa7-8c8b73d7db4f(1).pdf
Instructions/87b97616-7a9c-4e32-bb7d-2ce83a83cff7(1).pdf
Instructions/82bd03aa-5e27-4c94-bd3e-b49418e60edb(1).pdf
Instructions/5caffe56-b932-453d-977d-f7a22a897703(1).pdf
Instructions/d5bd0846-59bb-4528-bf3c-f2bd86048fa6(1).pdf
Instructions/7bfdce68-c730-4d69-8613-b53dacb364c3(1).pdf
Instructions/7a7da85c-1964-48e5-b804-b11eb771dda3(1).pdf
Instructions/4c592294-7420-4c6e-8f60-721911f728e5(1).pdf
Instructions/f9f887a4-ba26-4cd4-b385-0c34453fc521(1).pdf
Instructions/bd1433a2-c290-4ca4-b4e6-5160fcaec66d(2).pdf