In [9]:
import os
import json
import pandas as pd
from IPython.display import HTML, display

In [10]:
folders = [
    "updated_instructions",
    "updated_ocr_instructions"
]

records = []

for folder in folders:
    for filename in os.listdir(folder):
        if not filename.lower().endswith(".json"):
            continue
        full_path = os.path.join(folder, filename)
        with open(full_path, "r", encoding="utf-8") as f:
            data = json.load(f)
        # удаляем символ '®'
        mnn = data.get("mnn", "").replace("®", "")
        trade_name = data.get("trade_name", "").replace("®", "")
        drug_id = data.get("drug_id", "").replace("®", "")
        file_name = data.get("file_name", "").replace("®", "")

        records.append({
            "mnn": mnn,
            "trade_name": trade_name,
            "drug_id": drug_id,
            "file_name": file_name
        })

df = pd.DataFrame(records, columns=["mnn", "trade_name", "drug_id", "file_name"])

df.sort_values(by="mnn", inplace=True)

df.reset_index(drop=True, inplace=True)

df.to_csv("instructions_metadata.csv", index=False, encoding="utf-8-sig")

print(f"Собрано записей: {len(df)}")

Собрано записей: 560

In [11]:
df

,mnn,trade_name,drug_id,file_name
0,Абемациклиб,Зенлистик,ca56c862-7110-4a8f-ad46-ecb8008f14f0,9636e639-9f46-4fb8-8d53-da4bddfd0c4b.pdf
1,Авелумаб,Бавенсио,858972d5-c364-4ecb-bfcd-7fae540ce594,9d3baa37-5171-4fb7-abfb-b53655cd0b22.pdf
2,Авелумаб,Бавенсио,38de6a87-82fe-442b-9636-a61d7738d121,863f6555-9a46-4720-bd87-9ee8ef3436aa.pdf
3,Азацитидин,Азацитидин Эльфа,349a4687-605b-45e2-aefc-ce8aab1d542c,afbee0f1-f99e-4c24-91d7-134606e2040b.pdf
4,Азацитидин,Джоцитадин,1e482f7b-49af-4412-8b8a-1d65ebed653d,59cb8af2-29ed-4c29-972e-19fa88d788be.pdf
...,...,...,...,...
555,Этопозид,Этопозид-Рус,f88e724e-e3c6-4d20-ad4f-5d16e4ede63b,74d2237b-6339-4cae-b37a-35665ba1710a.pdf
556,Этопозид,Ластет,82190c01-9445-4799-a905-c166ee76a7bc,414d73f5-29c7-4823-b2a4-a14b8fc57a0a.pdf
557,Этопозид,Фитозид,e34a2b2d-447a-4051-9651-cbb09f8882b9,8f9fba7f-fd02-4df2-9253-1845647e2cdf.pdf
558,Этопозид,Этопозид-ЛЭНС,a0f37a08-db3e-4095-97bc-fd8ac36b1262,dab68cee-1f2b-4687-bb76-96203800d17e.pdf
559,Этопозид,Этопозид,e57eef5f-321c-401a-b7e7-e9e7e77d7444,П_N012704_01[2011]_0.pdf

In [14]:
df = pd.read_csv("instructions_metadata.csv", encoding="utf-8-sig")

# нормализуем для подсчета истинного количество уникальных МНН и торговых названий
df["mnn_norm"] = df["mnn"].astype(str).str.lower().str.strip()
df["trade_norm"] = df["trade_name"].astype(str).str.lower().str.strip()

unique_mnn = df["mnn_norm"].nunique()
unique_trade = df["trade_norm"].nunique()

print(f"Уникальных MNN: {unique_mnn}")
print(f"Уникальных trade_name: {unique_trade}")

Уникальных MNN: 132
Уникальных trade_name: 446

**Таблица с количеством инструкций по каждому MNN**

In [22]:
pd.set_option('display.max_rows', None)

df = pd.read_csv("instructions_metadata.csv", encoding="utf-8-sig")

df["mnn"] = df["mnn"].astype(str).str.strip()
df["trade_name"] = df["trade_name"].astype(str).str.strip()

trade_counts = (
    df
    .groupby("mnn")["trade_name"]
    .count()
    .sort_values(ascending=False)
    .reset_index(name="trade_name_count")
)

avg_trade_per_mnn = trade_counts["trade_name_count"].mean()
print(f"Среднее число торговых названий на одно MNN: {avg_trade_per_mnn:.2f}\n")

display(trade_counts)

Среднее число торговых названий на одно MNN: 4.24

                                       mnn  trade_name_count
0                                 Этопозид                10
1                              Бикалутамид                10
2                              Карбоплатин                10
3                      Интерферон альфа-2b                10
4                                 Иматиниб                10
5                               Доцетаксел                10
6                                 Летрозол                10
7                              Метотрексат                10
8                              Паклитаксел                10
9                               Гемцитабин                10
10                            Кабазитаксел                10
11                              Винорелбин                10
12                              Бортезомиб                10
13                               Сунитиниб                10
14                             Капецитабин                10
15                             Фулвестрант                10
16                              Эверолимус                10
17                              Иринотекан                 9
18                            Доксорубицин                 9
19                              Анастрозол                 9
20                               Пазопаниб                 9
21                             Пеметрексед                 9
22                               Сорафениб                 9
23                             Бендамустин                 9
24                               Третиноин                 9
25                             Темозоломид                 9
26                              Тамоксифен                 8
27                              Флударабин                 8
28                              Фторурацил                 8
29                              Азацитидин                 8
30                            Оксалиплатин                 8
31                             Трастузумаб                 8
32                             Трипторелин                 7
33                               Цисплатин                 7
34                           Циклофосфамид                 7
35                             Палбоциклиб                 6
36                               Гозерелин                 6
37                                Флутамид                 6
38                               Бусерелин                 6
39                               Кладрибин                 6
40                               Децитабин                 6
41                               Эрлотиниб                 6
42                               Лапатиниб                 6
43                               Блеомицин                 5
44                               Акситиниб                 5
45                             Карфилзомиб                 5
46                                Мелфалан                 5
47                               Ибрутиниб                 5
48                              Эпирубицин                 5
49                               Митомицин                 5
50                               Цитарабин                 5
51                             Лейпрорелин                 4
52                            Руксолитиниб                 4
53                              Ленватиниб                 4
54                             Бевацизумаб                 4
55                        Гидроксикарбамид                 4
56                               Бусульфан                 4
57                            Даунорубицин                 4
58                               Ифосфамид                 3
59                              Пертузумаб                 3
60                             Трабектедин                 3
61                           Пембролизумаб                 3
62                           Меркаптопурин                 3
63                               Топотекан                 3
64                              Дакарбазин                 3
65                             Осимертиниб                 3
66                                Олапариб                 3
67                            Дактиномицин                 3
68                                Афатиниб                 3
69                             Даратумумаб                 3
70                             Треосульфан                 3
71                            Кабозантиниб                 3
72                            Аспарагиназа                 3
73                              Цетуксимаб                 2
74                              Идарубицин                 2
75                             Венетоклакс                 2
76                              Висмодегиб                 2
77                             Селуметиниб                 2
78                              Рибоциклиб                 2
79                               Торемифен                 2
80                             Пролголимаб                 2
81                              Вандетаниб                 2
82                              Эксеместан                 2
83                              Клофарабин                 2
84                              Кризотиниб                 2
85                                 Тегафур                 2
86                            Митоксантрон                 2
87                           Ларотректиниб                 2
88   Арабинопиранозилметил нитрозомочевина                 2
89                                Авелумаб                 2
90                             Хлорамбуцил                 2
91                             Афлиберцепт                 2
92                                Ломустин                 2
93                    Брентуксимаб ведотин                 1
94                               Алектиниб                 1
95                            Темсиролимус                 1
96                            Атезолизумаб                 1
97                                 Тиотепа                 1
98                               Алпелисиб                 1
99                            Блинатумомаб                 1
100                            Вемурафениб                 1
101                             Элотузумаб                 1
102                             Траметиниб                 1
103                              Церитиниб                 1
104                             Апалутамид                 1
105                            Прокарбазин                 1
106                            Талазопариб                 1
107                  Гемтузумаб озогамицин                 1
108                             Ипилимумаб                 1
109                              Кармустин                 1
110                              Иксазомиб                 1
111                            Иксабепилон                 1
112                            Кобиметиниб                 1
113                             Дурвалумаб                 1
114               Диглицидил метилфосфонат                 1
115                             Лорлатиниб                 1
116                             Дегареликс                 1
117                            Мидостаурин                 1
118                              Неларабин                 1
119                              Ниволумаб                 1
120                             Нинтеданиб                 1
121                           Обинутузумаб                 1
122                             Дабрафениб                 1
123                   Паклитаксел+альбумин                 1
124                           Гилтеритиниб                 1
125                            Панитумумаб                 1
126                    Полатузумаб ведотин                 1
127                              Понатиниб                 1
128                            Рамуцирумаб                 1
129                            Регорафениб                 1
130                      Гидразина сульфат                 1
131                            Абемациклиб                 1